var request = require("request");
var fs = require("fs");
var cheerio = require('cheerio');
var _ = require('underscore');
var JSONArray = [];


var getMITDepartments = function(callback) {
	var deptObjects = [];
	var courseObj = {};

	request({
		uri: "http://ocw.mit.edu/courses/find-by-department/"
		}, function(error, response, body) {
			var $ = cheerio.load(body);

			$('ul.deptList').children().children().each(function(){
				courseObj.subject = this.text();
				courseObj.departmentLink = 'http://ocw.mit.edu' + this['0'].attribs.href;
				deptObjects.push(courseObj);
				courseObj = {};
			});
			
			_.each(deptObjects, function(element, index, list) {
				callback(element);
			});
	});
};


var getAllMITCourseLinks = function(courseObj) { // returns all the course links from the MIT courese page
	var deptObject = courseObj;
	deptObject['courses'] = [];
	var newObj = {};

	request({
		uri: deptObject.departmentLink
		}, function(error, response, body) {
			var $ = cheerio.load(body);
			var courseDomElements = $('a.preview');

			for (var i = 1; i < courseDomElements.length; i += 3) {
				newObj.courseLink = 'http://ocw.mit.edu/' + courseDomElements[i].attribs.href;
				newObj.courseStub = newObj.courseLink.split('/').pop();
				newObj.courseTitle = courseDomElements[i].children[0].data.trim().split('\n')[0];
				deptObject.courses.push(newObj);
				newObj = {};
			};

			getMITCourseMediaData(deptObject);

	});

};


var getMITCourseMediaData = function(deptObject) { // returns citation and media links from one coures page
	var data = {};
	var mediaData = deptObject;
	var notesLink;

	_.each(mediaData.courses, function(element, index, list) {
		request({
			uri: element.courseLink
		}, function(error, response, body) {
			var $ = cheerio.load(body);
			list[index].professor = '';
			if ($('#course_nav').text().indexOf('Lecture Notes') != -1) { // does the course have notes?
				notesLink = element.courseLink + '/lecture-notes/';
				if ($('p.ins').length > 1) {
					$('p.ins').each(function(i, element){
						i < $('p.ins').length - 1 ? list[index].professor = list[index].professor + $(element).text().trim() + ', ' : list[index].professor = list[index].professor + $(element).text().trim();
					});
				} else {
					list[index].professor = $('p.ins').text();
				}
				request({
					uri: notesLink
				}, function(error, response, body) {
					$ = cheerio.load(body);
					var noteURL;
					list[index].noteLinks = [];
					$('a').each(function () {
						var link = this['0'].attribs.href;
						if (link && link.indexOf('/lecture-notes/') !== -1 && link.indexOf('.pdf') !== -1) { // make sure it's a link to a PDF
							data.link = 'http://ocw.mit.edu' + link;
							data.fileName = this['0'].attribs.href.split('/').pop();
							list[index].noteLinks.push(data);
							data = {};
						}
					});
					_.each(mediaData.courses, function(element, index, list) {
						if (element.noteLinks && typeof element.noteLinks[0] !== 'function') {
							console.log(element);
							fs.writeFileSync(element.courseStub + '.json', JSON.stringify(element) + '\n', 'utf8');
						}
					});
				});
			};
		});

	});

};

getMITDepartments(getAllMITCourseLinks);

// var data = { subject: 'Urban Studies and Planning',
//   departmentLink: 'http://ocw.mit.edu/courses/urban-studies-and-planning',
//   courses:
//    [ { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-001j-introduction-to-urban-design-and-development-spring-2006',
//        courseTitle: 'Introduction to Urban Design and Development',
//        professor: 'Prof. Susan Silberberg-Robinson',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-002j-fundamentals-of-public-policy-fall-2004',
//        courseTitle: 'Fundamentals of Public Policy',
//        professor: 'Prof. Steve MeyerProf. David Laws',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/architecture/4-001j-cityscope-new-orleans-spring-2007',
//        courseTitle: 'CityScope: New Orleans',
//        professor: ' Cherie Miot AbbanatProf. J. Phillip ThompsonProf. John Fernandez',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-007-resolving-public-disputes-spring-2005',
//        courseTitle: 'Resolving Public Disputes',
//        professor: 'Prof. Judith Layzer',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-011-the-art-and-science-of-negotiation-spring-2006',
//        courseTitle: 'The Art and Science of Negotiation' },
//      { courseLink: 'http://ocw.mit.edu//courses/history/21h-405j-the-ancient-city-spring-2005',
//        courseTitle: 'The Ancient City' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-013j-american-urban-history-i-spring-2010',
//        courseTitle: 'American Urban History I' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-014j-american-urban-history-ii-fall-2011',
//        courseTitle: 'American Urban History II' },
//      { courseLink: 'http://ocw.mit.edu//courses/history/21h-104j-riots-strikes-and-conspiracies-in-american-history-fall-2010',
//        courseTitle: 'Riots, Strikes, and Conspiracies in American History' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-016j-the-once-and-future-city-spring-2006',
//        courseTitle: 'The Once and Future City' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-020-poverty-public-policy-and-controversy-fall-2003',
//        courseTitle: 'Poverty, Public Policy and Controversy' },
//      { courseLink: 'http://ocw.mit.edu//courses/special-programs/sp-721-d-lab-i-development-fall-2009',
//        courseTitle: 'D-Lab I: Development' },
//      { courseLink: 'http://ocw.mit.edu//courses/history/21h-234j-downtown-spring-2005',
//        courseTitle: 'Downtown' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-027-city-to-city-comparing-researching-and-writing-about-cities-new-orleans-spring-2011',
//        courseTitle: 'City to City: Comparing, Researching and Writing about Cities: New Orleans' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-027-city-to-city-comparing-researching-and-writing-about-cities-spring-2006',
//        courseTitle: 'City to City: Comparing, Researching and Writing about Cities',
//        professor: ' Cherie Miot Abbanat',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-122-environment-and-society-fall-2002',
//        courseTitle: 'Environment and Society' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-123-big-plans-spring-2003',
//        courseTitle: 'Big Plans' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-124-introduction-to-education-looking-forward-and-looking-back-on-education-fall-2011',
//        courseTitle: 'Introduction to Education: Looking Forward and Looking Back on Education' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-125-introduction-to-education-understanding-and-evaluating-education-spring-2009',
//        courseTitle: 'Introduction to Education: Understanding and Evaluating Education' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-126j-economics-of-education-spring-2007',
//        courseTitle: 'Economics of Education',
//        professor: 'Prof. Frank Levy',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-127j-computer-games-and-simulations-for-investigation-and-education-spring-2009',
//        courseTitle: 'Computer Games and Simulations for Investigation and Education' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-128-information-technology-and-the-labor-market-spring-2005',
//        courseTitle: 'Information Technology and the Labor Market',
//        professor: 'Prof. Frank Levy',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-129-educational-theory-and-practice-i-fall-2011',
//        courseTitle: 'Educational Theory and Practice I' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-131-educational-theory-and-practice-iii-spring-2012',
//        courseTitle: 'Educational Theory and Practice III' },
//      { courseLink: 'http://ocw.mit.edu//courses/sloan-school-of-management/15-031j-energy-decisions-markets-and-policies-spring-2012',
//        courseTitle: 'Energy Decisions, Markets, and Policies' },
//      { courseLink: 'http://ocw.mit.edu//courses/anthropology/21a-219-law-and-society-spring-2003',
//        courseTitle: 'Law and Society',
//        professor: 'Prof. Susan S. Silbey',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-164-human-rights-in-theory-and-practice-fall-2010',
//        courseTitle: 'Human Rights in Theory and Practice' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-165-infrastructure-and-energy-technology-challenges-fall-2011',
//        courseTitle: 'Infrastructure and Energy Technology Challenges' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-166-law-social-movements-and-public-policy-comparative-and-international-experience-spring-2012',
//        courseTitle: 'Law, Social Movements, and Public Policy: Comparative and International Experience' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-167-economic-development-technical-capabilities-spring-2004',
//        courseTitle: 'Economic Development &amp; Technical Capabilities',
//        professor: 'Prof. Alice Amsden',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-s196-global-freshwater-crisis-spring-2011',
//        courseTitle: 'Global Freshwater Crisis' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-310j-media-technology-and-city-design-and-development-spring-2002',
//        courseTitle: 'Media Technology and City Design and Development' },
//      { courseLink: 'http://ocw.mit.edu//courses/history/21h-234j-downtown-spring-2005',
//        courseTitle: 'Downtown' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-165-infrastructure-and-energy-technology-challenges-fall-2011',
//        courseTitle: 'Infrastructure and Energy Technology Challenges' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-166-law-social-movements-and-public-policy-comparative-and-international-experience-spring-2012',
//        courseTitle: 'Law, Social Movements, and Public Policy: Comparative and International Experience' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-s196-global-freshwater-crisis-spring-2011',
//        courseTitle: 'Global Freshwater Crisis' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-947-history-and-theory-of-historic-preservation-spring-2007',
//        courseTitle: 'History and Theory of Historic Preservation',
//        professor: 'Prof. Max Page',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-520-a-workshop-on-geographic-information-systems-fall-2005',
//        courseTitle: 'A Workshop on Geographic Information Systems',
//        professor: 'Prof. Joseph Ferreira',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-201-gateway-to-the-profession-of-planning-fall-2010',
//        courseTitle: 'Gateway to the Profession of Planning',
//        professor: 'Prof. Bishwapriya Sanyal',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-201-gateway-planning-action-fall-2007',
//        courseTitle: 'Gateway: Planning Action',
//        professor: 'Prof. Xavier de Souza Briggs',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-201-gateway-planning-action-fall-2005',
//        courseTitle: 'Gateway: Planning Action',
//        professor: ' Cherie Miot AbbanatProf. Lawrence ValeProf. Xavier de Souza BriggsProf. Annette M. KimProf. Balakrishnan Rajagopal',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-201-gateway-planning-action-fall-2002',
//        courseTitle: 'Gateway: Planning Action',
//        professor: 'Prof. Diane DavisProf. Langley KeyesProf. Lawrence Susskind',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-202-planning-economics-fall-2010',
//        courseTitle: 'Planning Economics' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-203-microeconomics-fall-2010',
//        courseTitle: 'Microeconomics' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-204-planning-communications-and-digital-media-fall-2004',
//        courseTitle: 'Planning, Communications, and Digital Media',
//        professor: 'Prof. Lorlene Hoyt',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-208-introduction-to-computers-in-public-management-ii-january-iap-2002',
//        courseTitle: 'Introduction to Computers in Public Management II',
//        professor: 'Prof. Joseph FerreiraProf. Lorlene Hoyt Thomas Grayson',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-220-quantitative-reasoning-statistical-methods-for-planners-i-spring-2009',
//        courseTitle: 'Quantitative Reasoning &amp; Statistical Methods for Planners I',
//        professor: ' Ezra Haber Glenn',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-225-argumentation-and-communication-fall-2006',
//        courseTitle: 'Argumentation and Communication',
//        professor: ' Cherie Miot Abbanat',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-229-advanced-writing-seminar-spring-2004',
//        courseTitle: 'Advanced Writing Seminar',
//        professor: ' Cherie Miot Abbanat',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-233-research-design-for-policy-analysis-and-planning-fall-2007',
//        courseTitle: 'Research Design for Policy Analysis and Planning' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-233-crafting-research-questions-and-qualitative-methodology-fall-2005',
//        courseTitle: 'Crafting Research Questions and Qualitative Methodology' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-235-analyzing-projects-and-organizations-fall-2009',
//        courseTitle: 'Analyzing Projects and Organizations' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-237-gender-and-race-work-and-public-policy-spring-2005',
//        courseTitle: 'Gender and Race, Work, and Public Policy' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-128-information-technology-and-the-labor-market-spring-2005',
//        courseTitle: 'Information Technology and the Labor Market',
//        professor: 'Prof. Frank Levy',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-126j-economics-of-education-spring-2007',
//        courseTitle: 'Economics of Education',
//        professor: 'Prof. Frank Levy',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-127j-computer-games-and-simulations-for-investigation-and-education-spring-2009',
//        courseTitle: 'Computer Games and Simulations for Investigation and Education' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-255-negotiation-and-dispute-resolution-in-the-public-sector-spring-2005',
//        courseTitle: 'Negotiation and Dispute Resolution in the Public Sector',
//        professor: 'Prof. Lawrence Susskind',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/sloan-school-of-management/15-342j-organizations-and-environments-fall-2004',
//        courseTitle: 'Organizations and Environments' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-301j-introduction-to-urban-design-and-development-fall-2006',
//        courseTitle: 'Introduction to Urban Design and Development',
//        professor: 'Prof. Dennis FrenchmanProf. Francisca Rojas',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-302j-urban-design-politics-spring-2010',
//        courseTitle: 'Urban Design Politics' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-304j-site-and-infrastructure-systems-planning-spring-2009',
//        courseTitle: 'Site and Infrastructure Systems Planning' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-307-beijing-urban-design-studio-summer-2008',
//        courseTitle: 'Beijing Urban Design Studio' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-307-beijing-urban-design-studio-summer-2006',
//        courseTitle: 'Beijing Urban Design Studio' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-308j-advanced-seminar-urban-nature-and-city-design-fall-2012',
//        courseTitle: 'Advanced Seminar: Urban Nature and City Design' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-309j-sensing-place-photography-as-inquiry-spring-2006',
//        courseTitle: 'Sensing Place: Photography as Inquiry',
//        professor: ' Alex MacLeanProf. Anne Whiston Spirn',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-309j-sites-in-sight-photography-as-inquiry-fall-2003',
//        courseTitle: 'Sites in Sight: Photography as Inquiry' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-310j-media-technology-and-city-design-and-development-fall-2002',
//        courseTitle: 'Media Technology and City Design and Development' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-328j-urban-design-skills-observing-interpreting-and-representing-the-city-fall-2004',
//        courseTitle: 'Urban Design Skills: Observing, Interpreting, and Representing the City' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-329-social-theory-and-the-city-fall-2005',
//        courseTitle: 'Social Theory and the City',
//        professor: 'Prof. Richard Sennett',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/architecture/4-241j-theory-of-city-form-spring-2004',
//        courseTitle: 'Theory of City Form',
//        professor: 'Prof. Julian Beinart',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/architecture/4-163j-urban-design-studio-providence-spring-2005',
//        courseTitle: 'Urban Design Studio: Providence' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-332j-urban-design-fall-2003',
//        courseTitle: 'Urban Design' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-333-urban-design-seminar-spring-2005',
//        courseTitle: 'Urban Design Seminar',
//        professor: 'Prof. Dennis FrenchmanProf. Susan Silberberg',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-337j-urban-design-policy-and-action-spring-2009',
//        courseTitle: 'Urban Design Policy and Action' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-337j-urban-design-policy-and-action-spring-2007',
//        courseTitle: 'Urban Design Policy and Action' },
//      { courseLink: 'http://ocw.mit.edu//courses/civil-and-environmental-engineering/1-463j-the-impact-of-globalization-on-the-built-environment-fall-2009',
//        courseTitle: 'The Impact of Globalization on the Built Environment',
//        professor: 'Mr. Derish M. WolffProf. Fred Moavenzadeh',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-360-community-growth-and-land-use-planning-fall-2010',
//        courseTitle: 'Community Growth and Land Use Planning' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-360-community-growth-and-land-use-planning-fall-2006',
//        courseTitle: 'Community Growth and Land Use Planning',
//        professor: 'Prof. Eran Ben-JosephProf. Terry Szold',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-360-community-growth-and-land-use-planning-fall-2005',
//        courseTitle: 'Community Growth and Land Use Planning',
//        professor: 'Prof. Eran Ben-JosephProf. Terry Szold',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-360-community-growth-and-land-use-planning-fall-2003',
//        courseTitle: 'Community Growth and Land Use Planning',
//        professor: 'Prof. Terry Szold',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-362-environmental-management-practicum-brownfield-redevelopment-fall-2006',
//        courseTitle: 'Environmental Management Practicum: Brownfield Redevelopment' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-363-civil-society-and-the-environment-spring-2005',
//        courseTitle: 'Civil Society and the Environment' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-364-international-environmental-negotiation-fall-2010',
//        courseTitle: 'International Environmental Negotiation' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-366j-planning-for-sustainable-development-spring-2006',
//        courseTitle: 'Planning for Sustainable Development',
//        professor: 'Prof. David LawsProf. Martin Rein',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-368-environmental-justice-fall-2004',
//        courseTitle: 'Environmental Justice' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-370-brownfields-policy-and-practice-fall-2005',
//        courseTitle: 'Brownfields Policy and Practice' },
//      { courseLink: 'http://ocw.mit.edu//courses/nuclear-engineering/22-081j-introduction-to-sustainable-energy-fall-2010',
//        courseTitle: 'Introduction to Sustainable Energy' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-373-science-politics-and-environmental-policy-fall-2004',
//        courseTitle: 'Science, Politics, and Environmental Policy',
//        professor: 'Prof. Judith Layzer',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-375-role-of-science-and-scientists-in-collaborative-approaches-to-environmental-policymaking-spring-2006',
//        courseTitle: 'Role of Science and Scientists in Collaborative Approaches to Environmental Policymaking',
//        professor: 'Dr. Herman Karl',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-380j-urban-transportation-planning-fall-2002',
//        courseTitle: 'Urban Transportation Planning',
//        professor: 'Prof. Frederick Salvucci Mikel Murga',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-401-introduction-to-housing-community-and-economic-development-fall-2004',
//        courseTitle: 'Introduction to Housing, Community and Economic Development',
//        professor: 'Prof. J. Phillip Thompson',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-401-introduction-to-housing-community-and-economic-development-fall-2003',
//        courseTitle: 'Introduction to Housing, Community and Economic Development' },
//      { courseLink: 'http://ocw.mit.edu//courses/political-science/17-188j-labor-and-politics-fall-2005',
//        courseTitle: 'Labor and Politics' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-421-housing-and-human-services-spring-2005',
//        courseTitle: 'Housing and Human Services',
//        professor: 'Prof. Langley KeyesProf. Martin Rein' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-422-downtown-management-organizations-fall-2006',
//        courseTitle: 'Downtown Management Organizations',
//        professor: 'Prof. Lorlene Hoyt',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-423-information-and-communication-technologies-in-community-development-spring-2004',
//        courseTitle: 'Information and Communication Technologies in Community Development',
//        professor: 'Prof. Langley KeyesProf. Lorlene Hoyt',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-431j-real-estate-finance-and-investment-fall-2006',
//        courseTitle: 'Real Estate Finance and Investment',
//        professor: 'Prof. David GeltnerProf. Tod McGrath',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-432j-real-estate-capital-markets-spring-2007',
//        courseTitle: 'Real Estate Capital Markets',
//        professor: 'Prof. David GeltnerProf. Tod McGrath',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-433j-real-estate-economics-fall-2008',
//        courseTitle: 'Real Estate Economics',
//        professor: 'Prof. William Wheaton',
//        noteLinks: [Object] },
//      { courseLink: 'http://ocw.mit.edu//courses/engineering-systems-division/esd-712-tools-for-analysis-design-for-real-estate-and-infrastructure-development-spring-2010',
//        courseTitle: 'Tools for Analysis: Design for Real Estate and Infrastructure Development' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-434j-advanced-topics-in-real-estate-finance-spring-2007',
//        courseTitle: 'Advanced Topics in Real Estate Finance',
//        professor: 'Prof. David Geltner' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-437-financing-economic-development-spring-2006',
//        courseTitle: 'Financing Economic Development',
//        professor: 'Prof. Karl Seidman' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-439-revitalizing-urban-main-streets-st-claude-avenue-new-orleans-spring-2009',
//        courseTitle: 'Revitalizing Urban Main Streets: St. Claude Avenue, New Orleans' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-439-revitalizing-urban-main-streets-hyde-jackson-square-roslindale-square-boston-spring-2005',
//        courseTitle: 'Revitalizing Urban Main Streets: Hyde/Jackson Square &amp; Roslindale Square, Boston',
//        professor: 'Prof. Karl SeidmanProf. Susan Silberberg' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-439-revitalizing-urban-main-streets-mission-hill-egleston-square-boston-spring-2003',
//        courseTitle: 'Revitalizing Urban Main Streets: Mission Hill &amp; Egleston Square, Boston',
//        professor: 'Prof. Karl SeidmanProf. Susan Silberberg' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-467j-property-rights-in-transition-spring-2005',
//        courseTitle: 'Property Rights in Transition',
//        professor: 'Prof. Annette M. Kim' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-469-urban-sociology-in-theory-and-practice-spring-2009',
//        courseTitle: 'Urban Sociology in Theory and Practice' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-471-targeting-the-poor-local-economic-development-in-developing-countries-spring-2010',
//        courseTitle: 'Targeting the Poor: Local Economic Development in Developing Countries' },
//      { courseLink: 'http://ocw.mit.edu//courses/special-programs/sp-721-d-lab-i-development-fall-2009',
//        courseTitle: 'D-Lab I: Development' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-479-water-and-sanitation-infrastructure-planning-in-developing-countries-spring-2005',
//        courseTitle: 'Water and Sanitation Infrastructure Planning in Developing Countries',
//        professor: 'Prof. Jennifer Davis' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-479j-water-and-sanitation-infrastructure-in-developing-countries-spring-2007',
//        courseTitle: 'Water and Sanitation Infrastructure in Developing Countries',
//        professor: ' Susan Murcott' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-481j-analyzing-and-accounting-for-regional-economic-growth-spring-2009',
//        courseTitle: 'Analyzing and Accounting for Regional Economic Growth',
//        professor: 'Prof. Karen R. Polenske' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-482j-regional-socioeconomic-impact-analyses-and-modeling-fall-2008',
//        courseTitle: 'Regional Socioeconomic Impact Analyses and Modeling' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-482j-regional-socioeconomic-impact-analyses-and-modeling-fall-2007',
//        courseTitle: 'Regional Socioeconomic Impact Analyses and Modeling' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-483-housing-and-land-use-in-rapidly-urbanizing-regions-fall-2011',
//        courseTitle: 'Housing and Land Use in Rapidly Urbanizing Regions' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-484-project-appraisal-in-developing-countries-spring-2005',
//        courseTitle: 'Project Appraisal in Developing Countries' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-486j-economic-institutions-and-growth-policy-analysis-fall-2005',
//        courseTitle: 'Economic Institutions and Growth Policy Analysis' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-487-urban-public-finance-in-developing-countries-fall-2004',
//        courseTitle: 'Urban Public Finance in Developing Countries' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-489-the-growth-and-spatial-structure-of-cities-fall-2005',
//        courseTitle: 'The Growth and Spatial Structure of Cities' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-491j-economic-development-policy-analysis-and-industrialization-fall-2004',
//        courseTitle: 'Economic Development, Policy Analysis, and Industrialization' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-493-legal-aspects-of-property-and-land-use-fall-2005',
//        courseTitle: 'Legal Aspects of Property and Land Use' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-164-human-rights-in-theory-and-practice-fall-2010',
//        courseTitle: 'Human Rights in Theory and Practice' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-501-introduction-to-technology-and-cities-fall-2002',
//        courseTitle: 'Introduction to Technology and Cities',
//        professor: 'Prof. Joseph Ferreira' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-520-a-workshop-on-geographic-information-systems-fall-2005',
//        courseTitle: 'A Workshop on Geographic Information Systems',
//        professor: 'Prof. Joseph Ferreira' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-521-spatial-database-management-and-advanced-geographic-information-systems-spring-2003',
//        courseTitle: 'Spatial Database Management and Advanced Geographic Information Systems',
//        professor: 'Prof. Joseph FerreiraProf. Lorlene Hoyt' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-522-research-seminar-on-urban-information-systems-fall-2005',
//        courseTitle: 'Research Seminar on Urban Information Systems',
//        professor: 'Prof. Joseph Ferreira' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-521-spatial-database-management-and-advanced-geographic-information-systems-spring-2003',
//        courseTitle: 'Spatial Database Management and Advanced Geographic Information Systems',
//        professor: 'Prof. Joseph FerreiraProf. Lorlene Hoyt' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-521-spatial-database-management-and-advanced-geographic-information-systems-spring-2003',
//        courseTitle: 'Spatial Database Management and Advanced Geographic Information Systems',
//        professor: 'Prof. Joseph FerreiraProf. Lorlene Hoyt' },
//      { courseLink: 'http://ocw.mit.edu//courses/civil-and-environmental-engineering/1-221j-transportation-systems-fall-2004',
//        courseTitle: 'Transportation Systems',
//        professor: 'Prof. Joseph Sussman' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-540j-urban-transportation-planning-fall-2006',
//        courseTitle: 'Urban Transportation Planning',
//        professor: 'Prof. Frederick Salvucci Justin Antos(Teaching Assistant) Mikel Murga' },
//      { courseLink: 'http://ocw.mit.edu//courses/civil-and-environmental-engineering/1-258j-public-transportation-systems-spring-2010',
//        courseTitle: 'Public Transportation Systems',
//        professor: 'Prof. Nigel Wilson John Attanucci' },
//      { courseLink: 'http://ocw.mit.edu//courses/civil-and-environmental-engineering/1-259j-transit-management-fall-2006',
//        courseTitle: 'Transit Management',
//        professor: 'Prof. Nigel Wilson' },
//      { courseLink: 'http://ocw.mit.edu//courses/civil-and-environmental-engineering/1-253j-transportation-policy-and-environmental-limits-spring-2004',
//        courseTitle: 'Transportation Policy and Environmental Limits',
//        professor: 'Prof. Frederick SalvucciProf. Joseph Coughlin' },
//      { courseLink: 'http://ocw.mit.edu//courses/civil-and-environmental-engineering/1-201j-transportation-systems-analysis-demand-and-economics-fall-2008',
//        courseTitle: 'Transportation Systems Analysis: Demand and Economics',
//        professor: ' Michael Frumin(Teaching Assistant)Prof. Moshe Ben-Akiva' },
//      { courseLink: 'http://ocw.mit.edu//courses/civil-and-environmental-engineering/1-201j-introduction-to-transportation-systems-fall-2006',
//        courseTitle: 'Introduction to Transportation Systems',
//        professor: 'Prof. Joseph SussmanProf. Nigel Wilson' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-601-introduction-to-environmental-policy-and-planning-fall-2005',
//        courseTitle: 'Introduction to Environmental Policy and Planning' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-701-introduction-to-international-development-planning-fall-2011',
//        courseTitle: 'Introduction to International Development Planning' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-701-introduction-to-international-development-planning-fall-2010',
//        courseTitle: 'Introduction to International Development Planning' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-701-introduction-to-planning-institutional-processes-in-developing-countries-fall-2003',
//        courseTitle: 'Introduction to Planning &amp; Institutional Processes in Developing Countries' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-800-doctoral-research-seminar-knowledge-in-the-public-arena-spring-2007',
//        courseTitle: 'Doctoral Research Seminar: Knowledge in the Public Arena',
//        professor: 'Prof. Frank LevyProf. Martin ReinProf. Xavier de Souza Briggs' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-902-advanced-urban-public-finance-collective-action-and-provisions-of-local-public-goods-spring-2009',
//        courseTitle: 'Advanced Urban Public Finance: Collective Action and Provisions of Local Public Goods' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-914-planning-communication-spring-2007',
//        courseTitle: 'Planning Communication',
//        professor: 'Prof. Deborah KobesProf. Langley KeyesProf. Susan SilberbergProf. Xavier de Souza Briggs' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-941-urban-climate-adaptation-spring-2011',
//        courseTitle: 'Urban Climate Adaptation' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-941-learning-by-comparison-first-world-third-world-cities-fall-2008',
//        courseTitle: 'Learning by Comparison: First World/Third World Cities' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-941-disaster-vulnerability-and-resilience-spring-2005',
//        courseTitle: 'Disaster, Vulnerability and Resilience',
//        professor: 'Prof. Jennifer LeaningProf. JoAnn Carmin' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-941-use-of-joint-fact-finding-in-science-intensive-policy-disputes-part-i-fall-2003',
//        courseTitle: 'Use of Joint Fact Finding in Science Intensive Policy Disputes, Part I',
//        professor: 'Dr. Herman KarlProf. Lawrence Susskind' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-942-regional-energy-environmental-economic-modeling-spring-2007',
//        courseTitle: 'Regional Energy-Environmental Economic Modeling' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-942-use-of-joint-fact-finding-in-science-intensive-policy-disputes-part-ii-spring-2004',
//        courseTitle: 'Use of Joint Fact Finding in Science Intensive Policy Disputes, Part II',
//        professor: 'Dr. Herman KarlProf. Lawrence Susskind' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-943-special-studies-in-urban-studies-and-planning-the-cardener-river-corridor-workshop-fall-2001',
//        courseTitle: 'Special Studies in Urban Studies and Planning - The Cardener River Corridor Workshop',
//        professor: 'Prof. Eran Ben-Joseph' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-943j-urban-transportation-land-use-and-the-environment-spring-2002',
//        courseTitle: 'Urban Transportation, Land Use, and the Environment',
//        professor: 'Prof. Pericles (Chris) Zegras' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-945-katrina-practicum-spring-2006',
//        courseTitle: 'Katrina Practicum',
//        professor: 'Prof. Ceasar McDowellProf. J. Phillip ThompsonProf. JoAnn Carmin' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-945-springfield-studio-fall-2005',
//        courseTitle: 'Springfield Studio',
//        professor: 'Prof. Ceasar McDowellProf. Karl Seidman' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-945-springfield-studio-spring-2004',
//        courseTitle: 'Springfield Studio' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-946-planning-in-transition-economies-for-growth-and-equity-spring-2004',
//        courseTitle: 'Planning in Transition Economies for Growth and Equity',
//        professor: 'Prof. Annette M. Kim' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-946j-beijing-urban-design-studio-summer-2004',
//        courseTitle: 'Beijing Urban Design Studio' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-947-urbanization-and-development-spring-2009',
//        courseTitle: 'Urbanization and Development' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-947-race-immigration-and-planning-spring-2005',
//        courseTitle: 'Race, Immigration, and Planning',
//        professor: 'Prof. J. Phillip ThompsonProf. Alethia Jones' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-947-sustainable-economic-development-spring-2004',
//        courseTitle: 'Sustainable Economic Development',
//        professor: 'Prof. Karl SeidmanProf. William Shutkin' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-947-new-century-cities-real-estate-digital-technology-and-design-fall-2004',
//        courseTitle: 'New Century Cities: Real Estate, Digital Technology, and Design',
//        professor: 'Prof. David GeltnerProf. Dennis Frenchman Susanne SeitingerProf. William Mitchell' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-947-imaging-the-city-the-place-of-media-in-city-design-and-development-fall-1998',
//        courseTitle: 'Imaging the City: The Place of Media in City Design and Development',
//        professor: 'Prof. Lawrence ValeProf. Sam Warner' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-948-the-politics-of-reconstructing-iraq-spring-2005',
//        courseTitle: 'The Politics of Reconstructing Iraq',
//        professor: 'Prof. Yosef Jabareen' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-948-power-of-place-media-technology-youth-and-city-design-and-development-spring-2001',
//        courseTitle: 'Power of Place: Media Technology, Youth, and City Design and Development' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-949-city-visions-past-and-future-spring-2004',
//        courseTitle: 'City Visions: Past and Future' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-949-cities-in-conflict-theory-and-practice-fall-2003',
//        courseTitle: 'Cities in Conflict: Theory and Practice' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-950-citizen-participation-community-development-and-urban-governance-in-the-developing-world-spring-2007',
//        courseTitle: 'Citizen Participation, Community Development, and Urban Governance in the Developing World',
//        professor: 'Prof. Gianpaolo Baiocchi' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-952-gaoming-studio-china-spring-2005',
//        courseTitle: 'Gaoming Studio - China' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-952-foshan-china-workshop-spring-2004',
//        courseTitle: 'Foshan China Workshop',
//        professor: 'Prof. Tunney LeeProf. Yu-Hung Hong' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-953-comparative-land-use-and-transportation-planning-spring-2006',
//        courseTitle: 'Comparative Land Use and Transportation Planning',
//        professor: 'Prof. Pericles (Chris) Zegras' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-954-community-owned-enterprise-and-civic-participation-spring-2005',
//        courseTitle: 'Community-Owned Enterprise and Civic Participation',
//        professor: 'Prof. J. Phillip Thompson' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-957-frameworks-of-urban-governance-january-iap-2007',
//        courseTitle: 'Frameworks of Urban Governance',
//        professor: 'Prof. Deborah Kobes' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-958-getting-things-implemented-strategy-people-performance-and-leadership-january-iap-2009',
//        courseTitle: 'Getting Things Implemented: Strategy, People, Performance, and Leadership',
//        professor: 'Prof. Xavier de Souza Briggs' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-959-reforming-natural-resources-governance-failings-of-scientific-rationalism-and-alternatives-for-building-common-ground-january-iap-2007',
//        courseTitle: 'Reforming Natural Resources Governance: Failings of Scientific Rationalism and Alternatives for Building Common Ground',
//        professor: 'Dr. David MattsonDr. Herman Karl' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-965-reflective-practice-an-approach-for-expanding-your-learning-frontiers-january-iap-2007',
//        courseTitle: 'Reflective Practice: An Approach for Expanding Your Learning Frontiers',
//        professor: 'Prof. Ceasar McDowell Claudia Canepa(Teaching Assistant) Sebastiao Ferriera' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-967-special-studies-in-urban-studies-and-planning-economic-development-planning-skills-january-iap-2007',
//        courseTitle: 'Special Studies in Urban Studies and Planning: Economic Development Planning Skills',
//        professor: 'Prof. Karl Seidman' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-969-workshop-on-deliberative-democracy-and-dispute-resolution-summer-2005',
//        courseTitle: 'Workshop on Deliberative Democracy and Dispute Resolution',
//        professor: 'Prof. Carrie Menkel-MeadowProf. David BooherProf. John ForesterProf. Judy InnesProf. Lawrence Susskind' },
//      { courseLink: 'http://ocw.mit.edu//courses/urban-studies-and-planning/11-975-feeding-cities-in-the-global-south-challenges-and-opportunities-for-action-in-cartagena-fall-2009',
//        courseTitle: 'Feeding Cities in the Global South: Challenges and Opportunities for Action in Cartagena' } ] };

// getMITCourseMediaData(data)

